"""Builds the v2 voiceover timeline from voice_plan.json.

    python3 voice.py plan     # no audio needed: timeline.json from the planned cut times (for previews)
    python3 voice.py build    # needs the 3 HeyGen wavs listed in voice_plan.json:
                              #   splices them into output/vo_v2.wav and writes timeline_final.json,
                              #   with cut points taken from the real pauses in the audio
"""
import itertools
import json
import os
import subprocess
import sys

import numpy as np
from scipy.io import wavfile

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, 'output')
SR = 48000
FRAME = 0.01        # analysis frame (s)
SIL_DB = -38.0      # below this (dBFS, 10 ms RMS) counts as silence


def load(path):
    tmp = os.path.join(OUT, '_tmp_load.wav')
    subprocess.run(['ffmpeg', '-y', '-loglevel', 'error', '-i', path, '-ac', '1', '-ar', str(SR), tmp], check=True)
    sr, x = wavfile.read(tmp)
    os.remove(tmp)
    return x.astype(np.float32) / 32768.0


def silent_mask(x):
    n = len(x) // int(FRAME * SR)
    fr = x[: n * int(FRAME * SR)].reshape(n, -1)
    db = 20 * np.log10(np.sqrt((fr ** 2).mean(axis=1)) + 1e-9)
    return db < SIL_DB


def silences(mask, lo, hi, min_len=0.06):
    """list of (start, end) silent spans inside [lo, hi] seconds"""
    out, i0 = [], None
    a, b = int(lo / FRAME), min(len(mask), int(hi / FRAME))
    for i in range(a, b):
        if mask[i] and i0 is None:
            i0 = i
        if (not mask[i] or i == b - 1) and i0 is not None:
            if (i - i0) * FRAME >= min_len:
                out.append((i0 * FRAME, i * FRAME))
            i0 = None
    return out


def speech_bounds(mask, lo, hi):
    idx = [i for i in range(int(lo / FRAME), min(len(mask), int(hi / FRAME))) if not mask[i]]
    return (idx[0] * FRAME, (idx[-1] + 1) * FRAME) if idx else (lo, hi)


def split_sentences(mask, region, expect):
    """split speech inside `region` into len(expect) sentences at the longest pauses whose
    resulting durations stay plausible versus the expected durations"""
    s0, s1 = speech_bounds(mask, *region)
    sil = [p for p in silences(mask, s0, s1) if p[0] > s0 + 0.3 and p[1] < s1 - 0.3]
    best, best_score = None, -1e9
    for combo in itertools.combinations(sil, len(expect) - 1):
        bounds = [s0] + [x for p in combo for x in p] + [s1]
        segs = [(bounds[2 * i], bounds[2 * i + 1]) for i in range(len(expect))]
        ratios = [(b - a) / e for (a, b), e in zip(segs, expect)]
        if min(ratios) < 0.55 or max(ratios) > 1.6:
            continue
        score = sum(p[1] - p[0] for p in combo) - 0.3 * sum(abs(r - 1) for r in ratios)
        if score > best_score:
            best, best_score = segs, score
    if best is None:
        raise SystemExit(f'could not find {len(expect)} sentences in {region}; check the audio')
    return best


def snap_edge(mask, t, direction):
    """move a cut point into silence (search up to 0.25 s; direction -1 = earlier, +1 = later)"""
    i = int(t / FRAME)
    for k in range(26):
        j = i + direction * k
        if 0 <= j < len(mask) and mask[j]:
            return j * FRAME
    return t


def timeline_from_cuts(plan, cuts):
    tempo, t = plan['tempo'], plan['lead']
    phrases, starts = {}, []
    for c in cuts:
        starts.append(t)
        for name, (a, b) in c['phrases'].items():
            phrases[name] = {'s': round(t + (a - c['s']) / tempo, 3), 'e': round(t + (b - c['s']) / tempo, 3),
                             'vo': plan['vo'][name]}
        t += (c['e'] - c['s']) / tempo + c.get('gap', plan['default_gap'])
    cues = {}
    for name, (src, st) in plan['word_cues'].items():
        for c, t0 in zip(cuts, starts):
            if c['src'] == src and c['s'] <= st < c['e']:
                cues[name] = round(t0 + (st - c['s']) / tempo, 3)
    end = round(phrases['cta']['e'] + plan['end_hold'], 2)
    return {'_note': 'generated by voice.py from voice_plan.json', 'end': end, 'phrases': phrases, 'cues': cues}


def resolve_cuts(plan, audio):
    masks = {k: silent_mask(v) for k, v in audio.items()}
    cuts, groups = [], {}
    for c in plan['cuts']:
        c = dict(c)
        m = masks[c['src']]
        sn = c.get('snap')
        if sn:
            key = (c['src'], tuple(sn['region']))
            if key not in groups:
                groups[key] = split_sentences(m, sn['region'], sn['expect'])
            a, b = groups[key][sn['index']]
            name = next(iter(c['phrases']))
            c['phrases'] = {name: [a, b]}
            c['s'], c['e'] = a - 0.04, b + 0.07
        else:
            c['s'], c['e'] = snap_edge(m, c['s'], -1), snap_edge(m, c['e'], +1)
        cuts.append(c)
    return cuts


def build():
    plan = json.load(open(os.path.join(ROOT, 'voice_plan.json')))
    audio = {}
    for k, v in plan['sources'].items():
        p = os.path.join(ROOT, v['file'])
        if not os.path.exists(p):
            sys.exit(f'missing {v["file"]} - download it from the audio_url in {v["timestamps"]}')
        audio[k] = load(p)
    cuts = resolve_cuts(plan, audio)
    tempo = plan['tempo']
    fade = int(0.008 * SR)
    parts = [np.zeros(int(plan['lead'] * tempo * SR), np.float32)]
    for c in cuts:
        seg = audio[c['src']][int(c['s'] * SR):int(c['e'] * SR)].copy()
        seg[:fade] *= np.linspace(0, 1, fade)
        seg[-fade:] *= np.linspace(1, 0, fade)
        parts += [seg, np.zeros(int(c.get('gap', plan['default_gap']) * tempo * SR), np.float32)]
    raw = os.path.join(OUT, 'vo_v2_spliced.wav')
    wavfile.write(raw, SR, (np.concatenate(parts) * 32767).astype(np.int16))
    subprocess.run(['ffmpeg', '-y', '-loglevel', 'error', '-i', raw, '-af',
                    f'atempo={tempo},highpass=f=80,acompressor=threshold=-20dB:ratio=3:attack=5:release=80,'
                    'loudnorm=I=-15:TP=-1.5:LRA=7', '-ar', str(SR), os.path.join(OUT, 'vo_v2.wav')], check=True)
    tl = timeline_from_cuts(plan, cuts)
    json.dump(tl, open(os.path.join(ROOT, 'timeline_final.json'), 'w'), ensure_ascii=False, indent=1)
    alignment_png(os.path.join(OUT, 'vo_v2.wav'), tl['phrases'], os.path.join(OUT, 'vo_alignment.png'))
    for c in cuts:
        print(f"{c['src']:4s} {c['s']:6.2f}-{c['e']:6.2f}  {', '.join(c['phrases'])}")
    print('voice ->', os.path.join(OUT, 'vo_v2.wav'), ' timeline_final.json  end', tl['end'])


def alignment_png(wav, phrases, out_png):
    """waveform of the spliced voice with each script line's span drawn on top (visual sync check)"""
    from PIL import Image, ImageDraw
    sr, a = wavfile.read(wav)
    a = a.astype(np.float32)
    dur = len(a) / sr
    w = 2400
    img = Image.new('RGB', (w, 360), 'white')
    d = ImageDraw.Draw(img)
    hop = max(1, len(a) // w)
    env = np.abs(a[: hop * w]).reshape(w, hop).max(axis=1)
    env = env / (env.max() + 1e-9)
    for x in range(w):
        d.line([(x, 180 - env[x] * 140), (x, 180 + env[x] * 140)], fill=(60, 60, 60))
    for k, (name, p) in enumerate(phrases.items()):
        x0, x1 = p['s'] / dur * w, p['e'] / dur * w
        col = (37, 211, 102) if k % 2 else (194, 24, 91)
        y = 330 if k % 2 == 0 else 30
        d.rectangle([x0, y, x1, y + 14], fill=col)
        d.text((x0 + 2, y - 14 if k % 2 == 0 else y + 16), name, fill=col)
    img.save(out_png)


if __name__ == '__main__':
    os.makedirs(OUT, exist_ok=True)
    mode = sys.argv[1] if len(sys.argv) > 1 else ''
    if mode == 'plan':
        plan = json.load(open(os.path.join(ROOT, 'voice_plan.json')))
        tl = timeline_from_cuts(plan, plan['cuts'])
        tl['_note'] = 'planned timing (estimated from HeyGen word timestamps); voice.py build replaces it with measured timing'
        json.dump(tl, open(os.path.join(ROOT, 'timeline.json'), 'w'), ensure_ascii=False, indent=1)
        for k, v in tl['phrases'].items():
            print(f"{k:11s} {v['s']:6.2f} {v['e']:6.2f}")
        print('end', tl['end'])
    elif mode == 'build':
        build()
    else:
        sys.exit(__doc__)
